version: '3.1'

services:

  order-service-db:
    image: 'postgres'
    ports:
      - "5433:5432"
    restart: always
    environment:
      POSTGRES_DB: order_service
      POSTGRES_PASSWORD: admin
    container_name: order-service-db